# Page settings

baseURL = "https://jashwanthgowda-resume.netlify.app/"
languageCode = "en"
title = "Jashwanth Gowda R"
enableGitInfo = false
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Jashwanth Gowda R"
    description = "Software Engineer - Flutter Developer"
    og_image = "better-software.png"
    twitterName = "@Jash_gowda_6"
    ghRepo = "https://github.com/Jashwanth-Gowda-R/resume"
    hugoRepo = "https://github.com/gohugoio/hugo/"

    [params.profile]
        enable = true
        name = "Jashwanth Gowda R"
        tagline = "Software Engineer - Flutter Developer"
        avatar = "jashu.jpg"

    [params.contact]
        enable = true

        location = "Bangalore,India"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+919986621042"
        text = "+919986621042"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:webdevjash6@gmail.com"
        text = "webdevjash6@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://jashwanthgowda.netlify.app/"
        text = "https://jashwanthgowda.netlify.app/"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical Skills "
        [[params.skills.list.items]]
        details="Flutter"
        [[params.skills.list.items]]
        details="Dart"
        [[params.skills.list.items]]
        details="Javascript"
        [[params.skills.list.items]]
        details="ReactJS"
        [[params.skills.list.items]]
        details="Riverpod"
        [[params.skills.list.items]]
        details="React-MUI"
        [[params.skills.list.items]]
        details="Bootstrap"
        [[params.skills.list.items]]
        details="Git"
        [[params.skills.list.items]]
        details="Firebase"
        [[params.skills.list.items]]
        details="Opencart"
        [[params.skills.list.items]]
        details="Wordpress"
        [[params.skills.list.items]]
        details="AWS (Amazon Web Services)"
        [[params.skills.list.items]]
        details="Apache"
        [[params.skills.list.items]]
        details="NGINX"



    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Bachelor of Telecommunication Engineering"
        university = "Don Bosco Institute Of Technology(VTU)"
        dates = "July. 2015 – May. 2019"


    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Professional Scrum Master™ I"
        body = "scrum.org"
        date = "2018"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Kannada"
        level = "Native Proficiency"

        [[params.languages.list]]
        name = "English"
        level = "Professional Working Proficiency"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Coding"

        [[params.interests.list]]
        name = "Cricket"

        [[params.interests.list]]
        name = "Fitness"


    [params.summary]
        enable = true
        text = "I am a self-taught Front-end Engineer with more than 2 years of industry experience. I am currently focusing on building both mobile and web applications using Flutter."


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineer -1, "
        dates = "July. 2021 – Nov. 2022"
        company = "Digital Green"
        details = "Developed and Implemented the below mobile and web application from the ground up :"
        [[params.experience.list.items]]
        details = "Developed a mobile-first application using Flutter to document the process of crop creation and create farmers’ profiles."
        [[params.experience.list.items]]
        details = " Involved in developing a datahub platform for enabling direct data sharing between organizations to prevent unintentional data misuse. Built the front-end of this application using ReactJS from the ground up with a small team of three engineers."
        [[params.experience.list.items]]
        details = "Responsible for bug fixes and documentation."

        [[params.experience.list]]
        title = "Software Engineer Intern"
        dates = "Oct. 2019 – April. 2021"
        company = " Vrook-Transforming Learning"
        details = "  Designed,Developed and Implemented the below web application from the ground up :"
        [[params.experience.list.items]]
        details = "Designed and developed custom mobile-responsive themes for OpenEdX LMS."
        [[params.experience.list.items]]
        details = "Implemented new features for booksbeka.com using OpenCart."
        [[params.experience.list.items]]
        details = "Designed and developed the company’s blogsite using GhostJS. "



    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Mishmi (Idu) Dictionary"
        meta = "Flutter,Dart"
        url = "https://play.google.com/store/apps/details?id=imcls.dictionary.demo_flutter"
        tagline = "It is Android application,the primary focus of this beginner-friendly dictionary is aimed at younger generations of the Mishmi (Idu) community. This initiative is towards the promotion and preservation of Mishmi (Idu) language. Involved in designing and developing an audio player corresponding to word in the entire app and worked on some frontend features in this app."

        [[params.projects.list]]
        title = "Vernacular Archive of Northeast India - VANI"
        meta = "Javascript,Sass,Bootstrap"
        url = "https://github.com/Jashwanth-Gowda-R/Project-Vani.github.io"
        tagline = "VANI for short - is an initiative aimed at documentation, digitization, and development of technology tools for the vernacular languages of Northeast India.Involved in designing and developing Mobile responsive theme customization for the website. "

        [[params.projects.list]]
        title = "Foodveda E-commerce Web Application"
        meta = "Opencart,Javascript,Mysql,Scss"
        url = "https://foodveda.in/"
        tagline = "This application was developed to help preserve traditional recipes and bring good health to consumers.Designed and developed this application using the OpenCart framework.Technologies used: Bootstrap, Sass,  Javascript, Opencart, MySQL    "


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Cooking, Beekeeping, Cycling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/Jashwanth-Gowda-R"
        title = "https://github.com/Jashwanth-Gowda-R"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/jashwanthgowda-6666"
        title = "https://www.linkedin.com/in/jashwanthgowda-6666"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "https://twitter.com/Jash_gowda_6"
        title = "https://twitter.com/Jash_gowda_6"
